version: '3'

services:
  redis:
    image: redis:4.0-alpine
    restart: always
    command: --port 6389
    volumes:
      - redis_billing:/data

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  billing_service:
    container_name: billing_service
    image: billing_service:last
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: billing.settings
      REDIS_HOST: redis
      REDIS_PORT: 6389
    volumes:
      # TODO: удалить этот volume
      - ./billing:/opt/project

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/log/nginx/:/var/log/nginx/
    depends_on:
      - billing_service


volumes:
  redis_billing:
