version: '3'

services:
  makemigrations:
    image: billing_service:last
    depends_on:
      - db
    command: "python manage.py makemigrations"
    environment:
      DJANGO_SETTINGS_MODULE: billing.settings
    volumes:
      - ./billing:/opt/project

  migrate:
    image: billing_service:last
    depends_on:
      - db
    command: "python manage.py migrate"
    environment:
      DJANGO_SETTINGS_MODULE: billing.settings

  test:
    image: billing_service:last
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    command: "python manage.py test"
    environment:
      DJANGO_SETTINGS_MODULE: billing.settings


volumes:
  redis_billing:
